### ISSUE TITLE
Mint 22: Running the non-distro specific package generates broken symlinks and fails

### ISSUE THREAD

**Issue by Zetteldude** [C0rn3j/sc-controller#11]
On Linux Mint 22, `./run.sh` creates broken symlinks that prevent the scripts from completing (and the program from running). 

This leads to errors like `OSError: ./libuinput.so: cannot open shared object file: No such file or directory` or `OSError: ./libhiddrv.so: cannot open shared object file: No such file or directory`. 

I suspect this is the same problem that causes the Noble appimages to never actually open, outputting `APPRUN_ERROR: No such file or directory` when executed from a terminal.

Manual solution: 
Editing the folder name in sc-controller-x.x.x.x/build from "lib.linux-x86_64-cpython-312" to "lib.linux-x86_64-3.12". Subsequently the not-broken symlinks all point to their respective .so normally contained in that folder.

**Comment by C0rn3j** [comment]
I have no clue if I did this properly, but it at least works on my system now.
