### ISSUE TITLE
Warning: `~/.config/scc/controller-icons` is missing

### ISSUE THREAD

**Issue by git-developer** [C0rn3j/sc-controller#41]
I encountered this message in the log:
```
W UDataManager  enumerate_children_finish for /userdata/system/.config/scc/controller-icons failed: g-io-error-quark: Error opening directory '/userdata/system/.config/scc/controller-icons': No such file or directory (1)
```

Environment: `sc-controller-v0.4.9.4-jammy-x86_64.AppImage`. `/userdata/system` is the `HOME` directory.

Unfortunately I can't tell the trigger for the warning.

**Comment by C0rn3j** [comment]
Have not tested, but it should not happen anymore.
