### ISSUE TITLE
Unable to open GUI after enabling "minimize to tray"

### ISSUE THREAD

**Issue by sudoharun** [C0rn3j/sc-controller#53]
Title. Doesn't work if I try to open with app launcher or with `scc gui` from terminal.

**Comment by C0rn3j** [comment]
Yeah that's unfortunate, in `~/.config/scc/config.json` set `minimize_on_start` and optionally `minimize_to_status_icon` to false, seems to be unable to recover from tray on left clicking.

**Comment by C0rn3j** [comment]
I've tagged 0.4.9.6 which has the fix, works on my setup.

**Comment by sudoharun** [comment]
Yes, I'm on wayland. I'm currently having issues with my systray so will report back when I can test this.
